// <auto-generated />
using InheritanceDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InheritanceDemo.Migrations
{
    [DbContext(typeof(SkoleContext))]
    [Migration("20260222103315_Nedarvning_Flere_Niveauer")]
    partial class Nedarvning_Flere_Niveauer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AfdelingTeacher", b =>
                {
                    b.Property<int>("AfdelingerAfdelingId")
                        .HasColumnType("int");

                    b.Property<int>("TeachersId")
                        .HasColumnType("int");

                    b.HasKey("AfdelingerAfdelingId", "TeachersId");

                    b.HasIndex("TeachersId");

                    b.ToTable("TeacherAfdeling", (string)null);
                });

            modelBuilder.Entity("FagStudent", b =>
                {
                    b.Property<int>("FagId")
                        .HasColumnType("int");

                    b.Property<int>("StuderendeId")
                        .HasColumnType("int");

                    b.HasKey("FagId", "StuderendeId");

                    b.HasIndex("StuderendeId");

                    b.ToTable("FagStudent");
                });

            modelBuilder.Entity("FagTeacher", b =>
                {
                    b.Property<int>("FagId")
                        .HasColumnType("int");

                    b.Property<int>("TeachersId")
                        .HasColumnType("int");

                    b.HasKey("FagId", "TeachersId");

                    b.HasIndex("TeachersId");

                    b.ToTable("TeacherFag", (string)null);
                });

            modelBuilder.Entity("InheritanceDemo.Models.Afdeling", b =>
                {
                    b.Property<int>("AfdelingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AfdelingId"));

                    b.Property<string>("AfdelingNavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AfdelingId");

                    b.ToTable("Afdelinger");
                });

            modelBuilder.Entity("InheritanceDemo.Models.Fag", b =>
                {
                    b.Property<int>("FagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FagId"));

                    b.Property<string>("FagTitel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FagId");

                    b.ToTable("Fag");
                });

            modelBuilder.Entity("InheritanceDemo.Models.Hold", b =>
                {
                    b.Property<int>("HoldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoldId"));

                    b.Property<string>("HoldNavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HoldId");

                    b.ToTable("Hold");
                });

            modelBuilder.Entity("InheritanceDemo.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Alder")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personer", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("InheritanceDemo.Models.Ansat", b =>
                {
                    b.HasBaseType("InheritanceDemo.Models.Person");

                    b.Property<int>("AfdelingId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaanedsLoen")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("AfdelingId");

                    b.ToTable("Ansatte", (string)null);
                });

            modelBuilder.Entity("InheritanceDemo.Models.Student", b =>
                {
                    b.HasBaseType("InheritanceDemo.Models.Person");

                    b.Property<int>("HoldId")
                        .HasColumnType("int");

                    b.HasIndex("HoldId");

                    b.ToTable("Studerende", (string)null);
                });

            modelBuilder.Entity("InheritanceDemo.Models.Teacher", b =>
                {
                    b.HasBaseType("InheritanceDemo.Models.Person");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("InheritanceDemo.Models.EUDStudent", b =>
                {
                    b.HasBaseType("InheritanceDemo.Models.Student");

                    b.Property<string>("Laereplads")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("EUDStuderende", (string)null);
                });

            modelBuilder.Entity("InheritanceDemo.Models.EUXStudent", b =>
                {
                    b.HasBaseType("InheritanceDemo.Models.Student");

                    b.Property<int>("Uddannelseslaengde")
                        .HasColumnType("int");

                    b.ToTable("EUXStuderende", (string)null);
                });

            modelBuilder.Entity("AfdelingTeacher", b =>
                {
                    b.HasOne("InheritanceDemo.Models.Afdeling", null)
                        .WithMany()
                        .HasForeignKey("AfdelingerAfdelingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InheritanceDemo.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FagStudent", b =>
                {
                    b.HasOne("InheritanceDemo.Models.Fag", null)
                        .WithMany()
                        .HasForeignKey("FagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InheritanceDemo.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StuderendeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FagTeacher", b =>
                {
                    b.HasOne("InheritanceDemo.Models.Fag", null)
                        .WithMany()
                        .HasForeignKey("FagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InheritanceDemo.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InheritanceDemo.Models.Ansat", b =>
                {
                    b.HasOne("InheritanceDemo.Models.Afdeling", "Afdeling")
                        .WithMany("Ansatte")
                        .HasForeignKey("AfdelingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InheritanceDemo.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("InheritanceDemo.Models.Ansat", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Afdeling");
                });

            modelBuilder.Entity("InheritanceDemo.Models.Student", b =>
                {
                    b.HasOne("InheritanceDemo.Models.Hold", "Hold")
                        .WithMany("Studerende")
                        .HasForeignKey("HoldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InheritanceDemo.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("InheritanceDemo.Models.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hold");
                });

            modelBuilder.Entity("InheritanceDemo.Models.Teacher", b =>
                {
                    b.HasOne("InheritanceDemo.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("InheritanceDemo.Models.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InheritanceDemo.Models.EUDStudent", b =>
                {
                    b.HasOne("InheritanceDemo.Models.Student", null)
                        .WithOne()
                        .HasForeignKey("InheritanceDemo.Models.EUDStudent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InheritanceDemo.Models.EUXStudent", b =>
                {
                    b.HasOne("InheritanceDemo.Models.Student", null)
                        .WithOne()
                        .HasForeignKey("InheritanceDemo.Models.EUXStudent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InheritanceDemo.Models.Afdeling", b =>
                {
                    b.Navigation("Ansatte");
                });

            modelBuilder.Entity("InheritanceDemo.Models.Hold", b =>
                {
                    b.Navigation("Studerende");
                });
#pragma warning restore 612, 618
        }
    }
}
