// <auto-generated />
using InheritanceDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InheritanceDemo.Migrations
{
    [DbContext(typeof(SkoleContext))]
    partial class SkoleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("AnsatSequence");

            modelBuilder.HasSequence("StudentSequence");

            modelBuilder.Entity("FagStudent", b =>
                {
                    b.Property<int>("FagId")
                        .HasColumnType("int");

                    b.Property<int>("StuderendeId")
                        .HasColumnType("int");

                    b.HasKey("FagId", "StuderendeId");

                    b.HasIndex("StuderendeId");

                    b.ToTable("FagStudent");
                });

            modelBuilder.Entity("InheritanceDemo.Models.Afdeling", b =>
                {
                    b.Property<int>("AfdelingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AfdelingId"));

                    b.Property<string>("AfdelingNavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AfdelingId");

                    b.ToTable("Afdelinger");
                });

            modelBuilder.Entity("InheritanceDemo.Models.Ansat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [AnsatSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int>("AfdelingId")
                        .HasColumnType("int");

                    b.Property<int>("Alder")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaanedsLoen")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AfdelingId");

                    b.ToTable("Ansatte");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("InheritanceDemo.Models.Fag", b =>
                {
                    b.Property<int>("FagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FagId"));

                    b.Property<string>("FagTitel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FagId");

                    b.ToTable("Fag");
                });

            modelBuilder.Entity("InheritanceDemo.Models.Hold", b =>
                {
                    b.Property<int>("HoldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoldId"));

                    b.Property<string>("HoldNavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HoldId");

                    b.ToTable("Hold");
                });

            modelBuilder.Entity("InheritanceDemo.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [StudentSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int>("Alder")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoldId")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HoldId");

                    b.ToTable("Studerende");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("FagStudent", b =>
                {
                    b.HasOne("InheritanceDemo.Models.Fag", null)
                        .WithMany()
                        .HasForeignKey("FagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InheritanceDemo.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StuderendeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InheritanceDemo.Models.Ansat", b =>
                {
                    b.HasOne("InheritanceDemo.Models.Afdeling", "Afdeling")
                        .WithMany("Ansatte")
                        .HasForeignKey("AfdelingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Afdeling");
                });

            modelBuilder.Entity("InheritanceDemo.Models.Student", b =>
                {
                    b.HasOne("InheritanceDemo.Models.Hold", "Hold")
                        .WithMany("Studerende")
                        .HasForeignKey("HoldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hold");
                });

            modelBuilder.Entity("InheritanceDemo.Models.Afdeling", b =>
                {
                    b.Navigation("Ansatte");
                });

            modelBuilder.Entity("InheritanceDemo.Models.Hold", b =>
                {
                    b.Navigation("Studerende");
                });
#pragma warning restore 612, 618
        }
    }
}
